### ISSUE TITLE
Codetable::lookup doesn't translate two-character codes

### ISSUE THREAD

**Issue by danpla** [manisandro/qtspell#1]
I noticed that two-character language codes ("en", "ru" ,etc.) are not translated in Qt version of gImageReader.

It seems like the problem is that Codetable::lookup, in contrast to gtksell, doesn't perform lookup for such codes at all.

Compare https://sourceforge.net/p/gtkspell/gtkspell/ci/master/tree/gtkspell/gtkspell-codetable.c#l199 with https://github.com/manisandro/qtspell/blob/3246b4b384878f0c97e868b6258b158781eb97ad/src/Codetable.cpp#L37

**Comment by manisandro** [comment]
Very true, thanks for reporting. Fixed in master, will make a new release soon.
