### ISSUE TITLE
Reproducible builds fails due to Doxyfile FULL_PATH_NAMES

### ISSUE THREAD

**Issue by ScarlettGatelyMoore** [manisandro/qtspell#10]
Please see https://tests.reproducible-builds.org/debian/issues/unstable/build_dir_in_documentation_generated_by_doxygen_issue.html

It is a simple fix.

``Index: qtspell-0.8.5/doc/Doxyfile.in
===================================================================
--- qtspell-0.8.5.orig/doc/Doxyfile.in	2018-06-15 04:20:29.000000000 -0700
+++ qtspell-0.8.5/doc/Doxyfile.in	2019-07-14 11:00:28.753465283 -0700
@@ -129,7 +129,7 @@
 # path before files name in the file list and in the header files. If set
 # to NO the shortest path that makes the file name unique will be used.
 
-FULL_PATH_NAMES        = YES
+FULL_PATH_NAMES        = NO
 
 # If the FULL_PATH_NAMES tag is set to YES then the STRIP_FROM_PATH tag
 # can be used to strip a user-defined part of the path. Stripping is
@@ -927,13 +927,13 @@
 # have to redo this when upgrading to a newer version of doxygen or when
 # changing the value of configuration settings such as GENERATE_TREEVIEW!
 
-HTML_HEADER            = 
+HTML_HEADER            =
 
 # The HTML_FOOTER tag can be used to specify a personal HTML footer for
 # each generated HTML page. If it is left blank doxygen will generate a
 # standard footer.
 
-HTML_FOOTER            = 
+HTML_FOOTER            =
 
 # The HTML_STYLESHEET tag can be used to specify a user-defined cascading
 # style sheet that is used by each HTML page. It can be used to

**Comment by manisandro** [comment]
Fixed in https://github.com/manisandro/qtspell/commit/89a74a3d1cacafe51795f019fcca336571302b8d, thanks.
