### ISSUE TITLE
Spell check doesn't work

### ISSUE THREAD

**Issue by tox-user** [manisandro/qtspell#6]
I'm using version 0.8.4 (a8f702b441119e71d5df92a8d2a5ec5a2ed5d933) on Debian and I can't get spell check to work. When I input words into a QTextEdit it doesn't highlight misspelled words. I have the needed dictionaries installed. Here is my code:

```
#include "mainwindow.h"
#include "ui_mainwindow.h"
#include <QTextEdit>
#include <QtSpell.hpp>

MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    // create a QtSpell::TextEdit instance
    QtSpell::TextEditChecker checker;

    // attach to a QTextEdit or QPlainTextEdit
    QTextEdit* textEdit = new QTextEdit(this);
    checker.setTextEdit(textEdit);
}
```

**Comment by manisandro** [comment]
Does the example [1] work? Do you get any messages printed on the terminal?

[1] https://github.com/manisandro/qtspell/tree/master/examples

**Comment by tox-user** [comment]
That worked! The issue was with how TextEditChecker is initialized. This line from readme file doesn't work:

```
// create a QtSpell::TextEdit instance
QtSpell::TextEditChecker checker;
```

needs to be replaced with:
```
QtSpell::TextEditChecker* checker = new QtSpell::TextEditChecker(this);
```

**Comment by manisandro** [comment]
I don't really think stack vs heap allocation makes a difference, unless your checker is going out of scope when stack allocated. This works fine:

    #include <QApplication>
    #include <QTextEdit>
    #include <QtSpell.hpp>

    int main(int argc, char* argv[]) {
        QApplication app(argc, argv);

        QtSpell::TextEditChecker checker;
        QTextEdit textEdit;
        checker.setTextEdit(&textEdit);
        checker.setDecodeLanguageCodes(true);
        checker.setShowCheckSpellingCheckbox(true);
        checker.setUndoRedoEnabled(true);

        textEdit.show();

        return app.exec();
    }

**Comment by tox-user** [comment]
That works too. So textEdit can't be a pointer?

**Comment by manisandro** [comment]
The relevant thing is not whether something is stack or heap allocated, but whether you correctly handle the life-time of an object. I.e.

    void foo() {
        QTextEdit stackEdit;
        QTextEdit* heapEdit = new QTextEdit();
        // Stack allocated stackEdit is destroyed when scope it was declared it ends
        // Heap allocated heapEdit lives beyond the scope of `foo`, until explicitly deleted
     }

If you not familiar with object lifetime and stack vs heap allocation, and specifically when dealing with QObject inherited classes, I recommend you read up on those topics.
